version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_PASSWORD: password
      MYSQL_USER: username
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"